spring:
  application:
    name: a-bootiful-client
#  sleuth:
#    sampler:
#      probability : 1.0
#  zipkin:
#    baseUrl: ${vcap.services.zipkin-server.credentials.uri:http://zipkin-server:9411}
#  rabbitmq:
#    host: rabbit-mq-service
    
eureka:
  client:
    enabled: false   
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-server-service:8761/eureka
#  instance:
#    hostname: a-bootiful-client
#    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
#        include: info, health, refresh
        include: hystrix.stream, info, health, refresh, threaddump

